// Host test harness for ESP8266SdFat auto-mount.
// Uses the HOST_MOCK DedicatedSpiCard to mount images generated by
// tests/generate_images.py.

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <PrintBasic.h>
typedef PrintBasic Print;
#include <SdFat.h>

uint8_t* _sdCard = nullptr;
uint64_t _sdCardSizeB = 0;
int64_t _sdReadFailSector = -1;

namespace {

struct TestCase {
    const char* image;
    bool expectMount;
    uint8_t expectedError;  // FsVolume::FsInitError value if expectMount==false
    uint8_t expectedFatType;  // 0 if not checked
    const char* checkFile;   // nullptr if not checked
    int64_t failSector;

    TestCase(const char* imagePath, bool mount, uint8_t error,
             uint8_t fatType, const char* file, int64_t readFailure = -1)
        : image(imagePath), expectMount(mount), expectedError(error),
          expectedFatType(fatType), checkFile(file),
          failSector(readFailure) {}
};

bool loadImage(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) {
        printf("FAIL: could not open %s\n", path);
        return false;
    }
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (size <= 0 || (size % 512) != 0) {
        printf("FAIL: invalid image size %ld for %s\n", size, path);
        fclose(f);
        return false;
    }
    if (_sdCard) {
        free(_sdCard);
    }
    _sdCard = (uint8_t*)malloc(size);
    if (!_sdCard || fread(_sdCard, 1, size, f) != (size_t)size) {
        printf("FAIL: could not read %s\n", path);
        free(_sdCard);
        _sdCard = nullptr;
        fclose(f);
        return false;
    }
    fclose(f);
    _sdCardSizeB = (uint64_t)size;
    return true;
}

bool runTest(const TestCase& tc) {
    printf("TEST: %-35s", tc.image);
    if (!loadImage(tc.image)) {
        return false;
    }
    _sdReadFailSector = tc.failSector;

    SdFs sd;
    bool ok = sd.begin(SdSpiConfig(0, DEDICATED_SPI, SD_SCK_MHZ(50)));
    uint8_t err = sd.initErrorCode();
    uint8_t ft = sd.fatType();

    if (ok != tc.expectMount) {
        printf("FAIL: mount=%s, expected=%s, error=%d, fatType=%d\n",
               ok ? "true" : "false", tc.expectMount ? "true" : "false",
               err, ft);
        return false;
    }
    if (!ok) {
        if (err != tc.expectedError) {
            printf("FAIL: error=%d, expected=%d\n", err, tc.expectedError);
            return false;
        }
        printf("PASS (no mount, error=%d)\n", err);
        return true;
    }
    if (tc.expectedFatType && ft != tc.expectedFatType) {
        printf("FAIL: fatType=%d, expected=%d\n", ft, tc.expectedFatType);
        return false;
    }
    if (tc.checkFile && !sd.exists(tc.checkFile)) {
        printf("FAIL: %s not found\n", tc.checkFile);
        return false;
    }
    printf("PASS (fatType=%d", ft);
    if (tc.checkFile) {
        printf(", found %s", tc.checkFile);
    }
    printf(")\n");
    return true;
}

bool runCurrentVolumeResetTest() {
    printf("TEST: %-35s", "failed begin clears current volume");
    _sdReadFailSector = -1;
    if (!loadImage("images/superfloppy_fat12.img")) {
        return false;
    }
    SdFs sd;
    if (!sd.begin(SdSpiConfig(0, DEDICATED_SPI, SD_SCK_MHZ(50)))) {
        printf("FAIL: initial mount did not set current volume\n");
        return false;
    }
    if (!loadImage("images/raw_zeros.img")) {
        return false;
    }
    FsFile file;
    if (sd.begin(SdSpiConfig(0, DEDICATED_SPI, SD_SCK_MHZ(50))) ||
        file.open("hello.txt")) {
        printf("FAIL: failed mount left stale current volume\n");
        return false;
    }
    printf("PASS\n");
    return true;
}

}  // namespace

int main() {
    const TestCase tests[] = {
        {"images/superfloppy_fat12.img", true, 0, FAT_TYPE_FAT12, "hello.txt"},
        {"images/superfloppy_fat16.img", true, 0, FAT_TYPE_FAT16, "hello.txt"},
        {"images/superfloppy_fat32.img", true, 0, FAT_TYPE_FAT32, "hello.txt"},
        {"images/superfloppy_exfat.img", true, 0, FAT_TYPE_EXFAT, "hello.txt"},
        {"images/mbr_4primary.img", true, 0, FAT_TYPE_FAT12, "hello.txt"},
        {"images/gpt_fat16_exfat.img", true, 0, FAT_TYPE_FAT16, "hello.txt"},
        {"images/gpt_linux_fat12.img", true, 0, FAT_TYPE_FAT12, "hello.txt"},
        {"images/raw_zeros.img", false,
         static_cast<uint8_t>(FsVolume::FsInitError::NoSupportedFileSystem),
         0, nullptr},
        {"images/protective_mbr_no_gpt.img", false,
         static_cast<uint8_t>(FsVolume::FsInitError::CorruptPartitionTable),
         0, nullptr},
        {"images/mbr_linux_only.img", false,
         static_cast<uint8_t>(FsVolume::FsInitError::NoSupportedFileSystem),
         0, nullptr},
        {"images/gpt_bad_crc.img", true, 0, FAT_TYPE_FAT12, nullptr},
        {"images/gpt_bad_entry_size.img", false,
         static_cast<uint8_t>(FsVolume::FsInitError::CorruptPartitionTable),
         0, nullptr},
        {"images/gpt_entry_size_384.img", true, 0,
         FAT_TYPE_FAT12, "hello.txt"},
        {"images/gpt_many_entries.img", true, 0,
         FAT_TYPE_FAT12, "hello.txt"},
        {"images/gpt_mismatched_backup.img", false,
         static_cast<uint8_t>(FsVolume::FsInitError::CorruptPartitionTable),
         0, nullptr},
        {"images/gpt_metadata_overlap.img", false,
         static_cast<uint8_t>(FsVolume::FsInitError::CorruptPartitionTable),
         0, nullptr},
        {"images/superfloppy_exfat_bad_checksum.img", false,
         static_cast<uint8_t>(FsVolume::FsInitError::NoSupportedFileSystem),
         0, nullptr},
        {"images/superfloppy_exfat_backup.img", true, 0,
          FAT_TYPE_EXFAT, "hello.txt"},
        {"images/superfloppy_exfat_backup_bpb.img", true, 0,
         FAT_TYPE_EXFAT, "hello.txt"},
        {"images/superfloppy_exfat_two_fats.img", false,
         static_cast<uint8_t>(FsVolume::FsInitError::NoSupportedFileSystem),
         0, nullptr},
        {"images/superfloppy_exfat_small_fat.img", false,
         static_cast<uint8_t>(FsVolume::FsInitError::NoSupportedFileSystem),
         0, nullptr},
        {"images/superfloppy_fat16_small_fat.img", false,
         static_cast<uint8_t>(FsVolume::FsInitError::NoSupportedFileSystem),
         0, nullptr},
        {"images/superfloppy_fat16_bad_layout.img", false,
         static_cast<uint8_t>(FsVolume::FsInitError::NoSupportedFileSystem),
         0, nullptr},
        {"images/mbr_malformed_ee.img", true, 0,
         FAT_TYPE_FAT12, "hello.txt"},
        {"images/mbr_4primary.img", true, 0,
         FAT_TYPE_FAT16, "hello.txt", 2048},
        {"images/gpt_fat16_exfat.img", true, 0,
         FAT_TYPE_FAT16, "hello.txt", 1},
        {"images/superfloppy_exfat.img", true, 0,
         FAT_TYPE_EXFAT, "hello.txt", 5},
        {"images/superfloppy_exfat.img", false,
         static_cast<uint8_t>(FsVolume::FsInitError::CardError),
         0, nullptr, 25},
    };

    int passed = 0;
    int total = sizeof(tests) / sizeof(tests[0]);
    for (int i = 0; i < total; i++) {
        if (runTest(tests[i])) {
            passed++;
        }
    }
    total++;
    if (runCurrentVolumeResetTest()) {
        passed++;
    }
    printf("\n%d/%d tests passed\n", passed, total);

    free(_sdCard);
    _sdCard = nullptr;
    return (passed == total) ? 0 : 1;
}
